### ISSUE TITLE
Hotspot offset

### ISSUE THREAD

**Issue by MFlisar** [afollestad/drag-select-recyclerview#12]
I'm using a `RecyclerView` that is lying under a transparent `Toolbar`. For this use case I would need to set an offset for the hotspot to be placed UNDERNEATH the toolbar instead of under the `Toolbar` (as the `RecyclerView` itself)

**Comment by afollestad** [comment]
You can already change the offset. Read the last section in the README.

**Comment by MFlisar** [comment]
You mean the `autoScrollHotspotHeight` setting? This is not what I mean.

I want following (all positions in relation to the corresponding `RecyclerView` and with a `autoScrollHotspotHeight` of 56dp):
* from 0dp to offset => nothing
* from offset + 56dp: the hotspot
* from `RecyclerView.getHeight()` - 56dp: the hotspot at the bottom

**Why?**

Because my `RecyclerView` is located UNDERNEATH (not under) the `Toolbar` and so I would like the hotspot to start underneath the toolbar as well. I would like the hotspot to be located at bottom of toolbar to bottom of toolbar + 56dp instead of top of `RecyclerView` to top of `RecyclerView` + 56dp

**Comment by afollestad** [comment]
https://github.com/afollestad/drag-select-recyclerview/releases/tag/0.3.4
