### ISSUE TITLE
Application crash on a possible java error

### ISSUE THREAD

**Issue by ghost** [afollestad/drag-select-recyclerview#18]
When you select some letter, if you imput the check and at the same time you press a letter, the app will be select a letter who was not selected. Infact, if you press ok the app will crash
[video.zip](https://github.com/afollestad/drag-select-recyclerview/files/228487/video.zip)

**Comment by afollestad** [comment]
Well what you said above really makes no sense at all, but there appears to be a crash in the sample project. I don't think it affects the library itself, just the sample.

**Comment by afollestad** [comment]
And I'm also not able to reproduce any crash problems in the sample application.
