### ISSUE TITLE
Drag selection end event

### ISSUE THREAD

**Issue by AleksandrKrasnoperov** [afollestad/drag-select-recyclerview#21]
Hi.
How i can catch "drag selection end" event?

SelectionListener has only onDragSelectionChanged method.

**Comment by oneroman** [comment]
@AleksandrKrasnoperov DragSelectRecyclerView has setFingerListener() method. probably you could use it to get event when user did ACTION_UP (means selection finished). does it work for you?

**Comment by AleksandrKrasnoperov** [comment]
Yes. Thanks.
