### ISSUE TITLE
Could not get 0.4.0 version

### ISSUE THREAD

**Issue by oneroman** [afollestad/drag-select-recyclerview#22]
I am able to use 0.3.5, 0.3.6 versions of the library but version 0.4.0 could not be downloaded by Gradle. Need to check that it properly published.

**Comment by afollestad** [comment]
0.4.0 hasn't been published, that was a typo.

**Comment by afollestad** [comment]
Sorry, it has actually

**Comment by idish** [comment]
Still unable to get the 0.4.0 version off gradle, is it going to be fixed soon?

**Comment by afollestad** [comment]
The latest is 0.3.6.

![capture](https://cloud.githubusercontent.com/assets/1820165/22381216/55b16946-e486-11e6-803f-163bfec36d0f.PNG)

**Comment by idish** [comment]
The github repository says that there is an available 0.4.0 release available, I guess it should be fixed then?
