### ISSUE TITLE
autoscroll doesn't work when DragSelectRecyclerView is inside NestedScrollView

### ISSUE THREAD

**Issue by nocturne9op2** [afollestad/drag-select-recyclerview#23]
I was trying to add a header to the DragSelectRecyclerView by placing it and a View that contains the header inside a NestedScrollView. Unfortunately, with this setup, the auto-scroll when drag selecting items doesn't work.

**Comment by afollestad** [comment]
That's to be expected really. Scroll views don't mix well, generally. NestedScrollView goes in a ScrollView, not the other way around, also.

**Comment by nocturne9op2** [comment]
I've managed to add a header directly to the DragSelectRecyclerView, I thought I would have to mess with the source code but isIndexSelectable() made things easier. Thanks for the library!
