### ISSUE TITLE
Return index of currently pressed item when drag seleting

### ISSUE THREAD

**Issue by nocturne9op2** [afollestad/drag-select-recyclerview#24]
Is there a way to do this atm?

**Comment by KishorAndroid** [comment]
Do you mean last selected item index?

**Comment by nocturne9op2** [comment]
yes, the last selected item would be the currently pressed item when drag selecting

**Comment by KishorAndroid** [comment]
I think you can easily get it by retrieving last array element from following function

`public final Integer[] getSelectedIndices() {
        ...
    }`

**Comment by nocturne9op2** [comment]
ahhh I see, calling getSelectedIndices() in onDragSelectionChanged would do it, thank you!
