### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by ArmChilingarov** [afollestad/drag-select-recyclerview#26]
Hello Dear .I am getting this issue . Please help me to find the solution.

java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 2(offset:2).state:3

[this is the bug in StackOverflow for more info](http://stackoverflow.com/questions/30220771/recyclerview-inconsistency-detected-invalid-item-position)

![screen shot 2017-05-08 at 11 58 35](https://cloud.githubusercontent.com/assets/28526900/25795340/f24df928-33e5-11e7-9fdb-94d52d889882.png)
![screen shot 2017-05-08 at 11 59 23](https://cloud.githubusercontent.com/assets/28526900/25795339/f24c71a2-33e5-11e7-871e-328ad7cdf131.png)

**Comment by afollestad** [comment]
That means you modified data without notifying the adapter.
