### ISSUE TITLE
How should creating the box on the top when you select items?

### ISSUE THREAD

**Issue by Alexaalex93** [afollestad/drag-select-recyclerview#27]
I'm beginning to develop in Android, for now I'm doing easy apps and I have a question.
How should creating the box on the top when you select items?. I mean, when you make a selection on box with a label appear on the top of the screen. You references that in the constructor of onBindHolder function, but I don't know how is defined in the XML file. If you could help me it would be really helpful.
Thanks.

Regards

**Comment by afollestad** [comment]
Sorry, implementation is up to you.

**Comment by afollestad** [comment]
PhotoAffix has more examples of showing checked indicators. https://github.com/afollestad/photo-affix
