### ISSUE TITLE
About can't import  DragSelectRecyclerViewAdapter

### ISSUE THREAD

**Issue by SiXuManYan** [afollestad/drag-select-recyclerview#28]
Deat Sir, Your DragSelectRecyclerViewAdapter is referenced many times in my project, but after you update the version, DragSelectRecyclerViewAdapter.java was deleted, causing my project to not run. Could you please restore it for reference, thank you sir.
My email address: itshiwei@aliyun.com

###### Include the following:
 - Library version: `com.afollestad:drag-select-recyclerview:1.0.0`
```java
import com.afollestad.dragselectrecyclerview.DragSelectRecyclerViewAdapter;
```
 
###### Reproduction Steps
compile 'com.afollestad:drag-select-recyclerview:+'

###### Expected Result
import succefull

###### Actual Result
import failure:Cannot resolve symbol 'DragSelectRecyclerViewAdapter

**Comment by afollestad** [comment]
You'll need to use an old version, this is not a bug. The class was removed.

**Comment by afollestad** [comment]
https://github.com/afollestad/drag-select-recyclerview/releases/tag/1.0.0
