### ISSUE TITLE
Android Studio can't find library classes

### ISSUE THREAD

**Issue by nonsobiose** [afollestad/drag-select-recyclerview#35]
Hello, I tried using the latest version (2.3.0), but upon a successful Gradle build, the DragSelectRecyclerView class becomes unvailable.
I can no longer see the Recyclerview in my XML layout nor have access to it in code.

**Comment by afollestad** [comment]
Your app needs to use AndroidX.

**Comment by afollestad** [comment]
Maybe it's a Proguard issue in your app? Or R8.

**Comment by afollestad** [comment]
Oh! You're trying to use `DragSelectRecyclerView`? That's been gone for awhile.

**Comment by afollestad** [comment]
Since 2.0.0, to be exact. https://github.com/afollestad/drag-select-recyclerview/releases/tag/2.0.0
