### ISSUE TITLE
Are there alternative of OnItemActivatedListener options for handling an item clicking?

### ISSUE THREAD

**Issue by proninyaroslav** [afollestad/drag-select-recyclerview#36]
Hi. I know that with the help of `OnItemActivatedListener` I can handle an item click in order to, for example, open it.

But there is a problem: it doesn't work if there are additional buttons in the item (pause button, menu, etc.). Their click event simply catched with the `OnItemActivatedListener` and I can't recognize if the pause button was pressed or the item was pressed.

As a workaround, I can use `(X, Y)` coords from `MotionEvent` to determine which element was clicked, but this method looks ugly. Is there a more elegant way?

**Comment by afollestad** [comment]
I'm not sure what you mean. Set normal click listeners to your items.

**Comment by proninyaroslav** [comment]
The click listener triggers during item selection.

**Comment by afollestad** [comment]
Are you trying to override clicks during selection mode? Long press is used to start item selection mode.

**Comment by proninyaroslav** [comment]
I set the listener in `onBindViewHolder` method. As far as I know, the problem is that `SelectionTracker.Builder` installs own `OnItemTouchListener` in `RecyclerView`. That is, it handles all events (touch, click, double click, etc) at the top level and provides the only way to handle click (e.g for opening item) - `OnItemActivatedListener`. 

When I use the regular `OnClickListener`, `SelectionTracker` handles a touch event (to select an item in selection mode) and then re-translates it below to my listener. Click listener is triggered even in selection mode.

**Comment by afollestad** [comment]
I haven't experienced any issues using regular click listeners in any use case.

**Comment by proninyaroslav** [comment]
Please check `1.1.0` version of `SelectionTracker`.
