### ISSUE TITLE
Range selection logic tweaks

### ISSUE THREAD

**Issue by MFlisar** [afollestad/drag-select-recyclerview#4]
If you long press an item and move to some other items and now have some already selected items in this range and then move back to the first item and a previously already selected item now falls out of the selected range, this item is unselected.

When ending the selection mode on the item I started it I would expect the selection to stay unchanged.

Therefore it would be good to remember those items and don't unchecked them if they fall out of the selection range...

Still there are some other cases to think of. If you start on an already selected item you could invert the selection mode and deselect the items in the range... think of a button which selects all items, then you could deselect a range in them...

Actually I'm not sure what is the most expected behaviour in such special cases, but at least I really expect to cancel the complete selection process if I stop the selection mode on the first item no matter how much if dragged around...

**Comment by afollestad** [comment]
Looking back at this, I'm not totally sure what you mean.

**Comment by MFlisar** [comment]
Actually, I'm using my own implementation currently, but what I meant was following: Consider a list like following:

**First thing**

Item1 ✓
Item2 ✓
Item3 ✓
Item4
Item5
Item6
Item7
Item8

Now you start a drag selection on item4, move to item3 and move back to item4 and expect, that you did not change the selection, as you stop the progress on the item you started, but you will have changed it, item3 will be unchecked...

**Second thing**

When you select all items, it would be a nice feature, if you could deselect a range in the selection with the swipe selection

**Comment by afollestad** [comment]
Haven't had a lot of time to work on this, sorry.

For the first behavior you mentioned (ending on the item you started with), I copied how Google Photos behaves. The initial item will become selected even if nothing else was selected.
