### ISSUE TITLE
Tags/index concern

### ISSUE THREAD

**Issue by plusCubed** [afollestad/drag-select-recyclerview#6]
We can rename the issue later, but the tag system used to mark the indices of the views is concerning because RecyclerView is not intended to work that way. With the option to change/move views without rebinding, it is very possible this can cause problems.

Just something to keep in mind if weird problems crop up in people's projects. Research needed. I'll investigate further once I start implementing this in Impression.

**Comment by eneim** [comment]
You can refer my comment in #5 , about using tags and my way to implement click events in RecyclerView. Hope that makes sense.

**Comment by plusCubed** [comment]
@eneim Well, of course, using the ViewHolder's methods is the obvious solution - I haven't looked over the code much to determine if that is possible or hampers anything, but since you're using it in your implementation, I'm assuming it is fine. In which case we should probably use that.

Or just support data sets with stable IDs. Since the library now stores the selected indices, that would also get messed up with the individual notify methods - stable IDs would mean much simpler code (only notifyDataSetChanged) and using IDs for the selections. 

Then there's the question of using payloads for activation/deactivation for performance. This all might start getting messy depending on how much control developers using the library want. There was an earlier pull request on putting everything into helper classes - that might be something to look into again.

In any case, I haven't taken much of a look at the code yet, so those solutions might not be possible.

**Comment by plusCubed** [comment]
There's some additional info in the docs on this stuff and in this talk by Yigit and Chet on the internals/usage of RecyclerView: https://www.youtube.com/watch?v=imsr8NrIAMs.

**Comment by eneim** [comment]
I didn't mean only using ViewHolder is enough, I think using the layoutPosition and adapterPosition along with each other is the way to go. I didn't watch the whole talk sadly, but yes It is a must :D.

**Comment by afollestad** [comment]
@plusCubed we are currently using getAdapterPosition() to retrieve item indicies. If there's a way to retrieve view holders from the RecyclerView without storing them as tags, that would be great.

**Comment by eneim** [comment]
@afollestad I think you miss the following methods:

```RecyclerView#findViewHolderForLayoutPosition(int)```
```RecyclerView#findViewHolderForAdapterPosition(int)```

**Comment by afollestad** [comment]
@eneim I did indeed, thanks

Also thanks for that YouTube video, @plusCubed, that's really informative

**Comment by afollestad** [comment]
@eneim actually that won't fully work, you can't use those methods without knowing the position first

**Comment by afollestad** [comment]
Unfortunately I don't think there's a good way to not use tags, without increasing the implementation complexity for users quite a bit.

**Comment by afollestad** [comment]
Resolved in 1.0.0
