### ISSUE TITLE
Sample code: MainViewHolder should be static

### ISSUE THREAD

**Issue by eneim** [afollestad/drag-select-recyclerview#7]
Just a comment: your ```MainViewHolder``` class should be declared as static, this is a general Java practice though.

I think your motivation is to access ```MainAdapter#mCallback```, but you can do that in another way: setup OnClickListener and OnLongClickListener from inside the ```Adapter#onCreateViewHolder``` method.

**Comment by afollestad** [comment]
It's not too big of a deal, the sample works fine.

I'm pretty aware of general Java practice 😉

**Comment by eneim** [comment]
I agree it's not a big deal :D. Just to give a slightly better practice. If you make some stress test in production and your Adapter instance be cleared while you have access to your Viewholder instance (an async API call after call the click event for example). The inner member class will have trouble (and yet you aware of that too). Pardon me for taking notice of small stuff too many :D.

**Comment by afollestad** [comment]
Yeah, you're right, it's probably a good idea to change it just in case people follow the sample too closely 😀
