### ISSUE TITLE
ActionMode Title is not getting update when Dragging an item 

### ISSUE THREAD

**Issue by PrathameshKesarkar** [afollestad/drag-select-recyclerview#8]
@Override
    public void onDragSelectionChanged(int i) {
        mActionMode.setTitle(i+" items Checked");
    }
I why is this not  Updating the ContextualActionBar title

**Comment by afollestad** [comment]
There must be something else wrong in your code. 

If you run the sample project, you'll see the callback works fine.

**Comment by PrathameshKesarkar** [comment]
yes my bad I didn't added the listener kinda lame sorry for putting it as an issue great library though 
can u  tell me how u made RecyclerView auto Scroll cause Even I want a same kinda functionality
